title: Home Sweet Home
resources:
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/button-entity-row/button-entity-row.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /local/manual-plugins/card-tools/card-tools.js?v=2
    type: js
  - url: /local/manual-plugins/layout-card/layout-card.js?v=2
    type: js
views:
  - title: R채ume
    panel: true
    icon: mdi:home-heart

    cards:
      - type: "custom:layout-card"
        layout: horizontal
        cards:
          ######################################
          # Spalte links
          ######################################
          - type: vertical-stack
            cards:
              - type: horizontal-stack
                cards:
                  - type: light
                    entity: light.alle
                    name: Alles
                  - type: light
                    entity: light.wohnzimmer
                    name: Wohnzimmer
                    icon: mdi:theater
              - type: horizontal-stack
                cards:
                  - type: light
                    entity: light.atelier
                    name: Atelier
                    icon: mdi:desk-lamp
                  - type: light
                    entity: light.cheminee
                    name: Cheminee
                    icon: mdi:fireplace
              - type: custom:mini-graph-card
                name: K체che
                lower_bound: 17
                upper_bound: 27
                show:
                  labels: true
                entities:
                  - sensor.kuche_sensor_temperature
                color_thresholds:
                  - value: 17
                    color: "#1F85DE"
                  - value: 22
                    color: "#2CD300"
                  - value: 24
                    color: "#C0392B"
              - type: custom:mini-graph-card
                name: Schlafzimmer
                lower_bound: 17
                upper_bound: 27
                show:
                  labels: true
                entities:
                  - sensor.netatmo_cheminee_temperature
                color_thresholds:
                  - value: 17
                    color: "#1F85DE"
                  - value: 22
                    color: "#2CD300"
                  - value: 24
                    color: "#C0392B"
          ######################################
          # Spalte mitte
          ######################################
          - type: vertical-stack
            cards:
              - type: horizontal-stack
                cards:
                  - type: light
                    entity: light.gang
                    name: Gang
                    icon: mdi:shoe-print
                  - type: light
                    entity: light.kuche
                    name: K체che
                    icon: mdi:stove
              - type: horizontal-stack
                cards:
                  - type: light
                    entity: light.bedroom
                    name: Schlafzimmer
                    icon: mdi:hotel
                  - type: light
                    entity: light.schlafzimmer_phil
                    name: Phil
                    icon: mdi:baby-carriage
              - type: custom:mini-graph-card
                name: Wohnzimmer
                lower_bound: 17
                upper_bound: 27
                show:
                  labels: true
                entities:
                  - sensor.netatmo_chino_temperature
                color_thresholds:
                  - value: 17
                    color: "#1F85DE"
                  - value: 22
                    color: "#2CD300"
                  - value: 24
                    color: "#C0392B"
              - type: custom:mini-graph-card
                name: Phil
                lower_bound: 17
                upper_bound: 27
                show:
                  labels: true
                entities:
                  - sensor.netatmo_schlafzimmer_temperature
                color_thresholds:
                  - value: 17
                    color: "#1F85DE"
                  - value: 22
                    color: "#2CD300"
                  - value: 24
                    color: "#C0392B"
          ######################################
          # Spalte rechts
          ######################################
          - type: vertical-stack
            cards:
              - type: entities
                entities:
                  - entity: light.wohnzimmer
                    name: Licht Wohnzimmer
                    icon: mdi:theater
                  - type: "custom:button-entity-row"
                    buttons:
                      - entity: scene.wohnzimmer_hell
                        icon: mdi:brightness-7
                      - entity: scene.clockwork_orange
                        icon: mdi:brightness-5
                      - entity: scene.wohnzimmer_relax
                        icon: mdi:brightness-4
                      - entity: scene.gaming
                        icon: mdi:gamepad-variant
                      - entity: scene.movie_menu
                        icon: mdi:movie-open
              - type: entities
                entities:
                  - entity: light.kuche
                    name: K체che
                    icon: mdi:stove
                  - type: "custom:button-entity-row"
                    buttons:
                      - entity: scene.kuche_hell
                        icon: mdi:brightness-7
                      - entity: scene.kuche_gedimmt
                        icon: mdi:brightness-6
                      - entity: scene.kuche_konzentration
                        icon: mdi:chef-hat
                      - entity: scene.kuche_nacht
                        icon: mdi:brightness-4
              - type: entities
                entities:
                  - entity: light.schlafzimmer
                    name: Schlafzimmer
                    icon: mdi:hotel
                  - type: "custom:button-entity-row"
                    buttons:
                      - entity: scene.schlafzimmer_hell
                        icon: mdi:brightness-7
                      - entity: scene.schlafzimmer_gedimmt
                        icon: mdi:brightness-6
                      - entity: scene.schlafzimmer_nacht
                        icon: mdi:brightness-4
                      - entity: scene.making_love
                        icon: mdi:heart-multiple
              - type: entities
                entities:
                  - entity: light.schlafzimmer_phil
                    name: Phil
                    icon: mdi:baby-carriage
                  - type: "custom:button-entity-row"
                    buttons:
                      - entity: scene.phil_nacht
                        icon: mdi:brightness-4
                      - entity: scene.phil_gedimmt
                        icon: mdi:brightness-6
                      - entity: scene.phil_hell
                        icon: mdi:brightness-7
             # CO2 & Luftfeuchtigkeit
              - type: vertical-stack
                cards:
                - type: horizontal-stack
                  cards:
                  - type: custom:mini-graph-card
                    name: Schlafzimmer
                    hours_to_show: 6
                    line_color: blue
                    line_width: 2
                    entities:
                      - sensor.netatmo_cheminee_co2
                  - type: custom:mini-graph-card
                    name: Wohnzimmer
                    hours_to_show: 6
                    line_color: red
                    line_width: 2
                    entities:
                      - sensor.netatmo_chino_co2
                  - type: custom:mini-graph-card
                    name: Phil
                    hours_to_show: 6
                    line_color: orange
                    line_width: 2
                    entities:
                      - sensor.netatmo_schlafzimmer_co2
                - type: horizontal-stack
                  cards:
                  - type: custom:mini-graph-card
                    name: Schlafzimmer
                    hours_to_show: 6
                    line_color: blue
                    line_width: 2
                    entities:
                      - sensor.netatmo_cheminee_humidity
                  - type: custom:mini-graph-card
                    name: Wohnzimmer
                    hours_to_show: 6
                    line_color: red
                    line_width: 2
                    entities:
                      - sensor.netatmo_chino_humidity
                  - type: custom:mini-graph-card
                    name: Phil
                    hours_to_show: 6
                    line_color: orange
                    line_width: 2
                    entities:
                      - sensor.netatmo_schlafzimmer_humidity
