title: Home Sweet Home
resources:
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/button-entity-row/button-entity-row.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/atomic_calendar/atomic_calendar.js
    type: module
  - url: /community_plugin/upcoming-media-card/upcoming-media-card.js?v=2
    type: js
  - url: /local/manual-plugins/card-tools/card-tools.js?v=2
    type: js
  - url: /local/manual-plugins/layout-card/layout-card.js?v=2
    type: js
views:
  - !include views/home.yaml
  - !include views/media.yaml
  - !include views/atmosphere.yaml
  - !include views/calendar.yaml
#  - !include views/power.yaml
#  - !include views/settings.yaml
#  - title: Network
#    path: network
#    icon: mdi:lan
#    cards:
#  - title: test
#    path: test
#    icon: mdi:test-tube
#    cards:
