# Switches automatically between a dark and a light theme depending on time of day
alias: 'Select theme based on sun state'
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
    to: above_horizon
  - platform: state
    entity_id: sun.sun
    to: below_horizon
action:
  - service_template: frontend.set_theme
    data_template:
      name: >
        {% if states.sun.sun.state == "above_horizon" %}
          Light - Orange
        {% else %}
          Navy Blue & Yellow
        {% endif %}
