- alias: 'Receiver Strom einschalten'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_movies", "on") or is_state("input_boolean.mediacontrol_cast", "on") or is_state("input_boolean.mediacontrol_ps4", "on") or is_state("input_boolean.mediacontrol_switch", "on") }}'
  action:
    service: script.power_on_recevier

- alias: 'Cinebar Strom einschalten'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_movies", "on") and float(states.sensor.strom_beamer.state) > 150 }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.powerstate_raspi

- alias: 'Beamer Strom einschalten'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_movies", "on") or is_state("input_boolean.mediacontrol_cast", "on") or is_state("input_boolean.mediacontrol_ps4", "on") or is_state("input_boolean.mediacontrol_switch", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.powerstate_beamer

- alias: 'Game Strom einschalten'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_switch", "on") or is_state("input_boolean.powercontrol_switch", "on") or is_state("input_boolean.mediacontrol_ps4", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.powerstate_game

- alias: 'Chromecast Strom einschalten'
  trigger:
    platform: template
    value_template: '{{ is_state("input_boolean.mediacontrol_cast", "on") }}'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.powerstate_chromecast
